[tool.poetry]
name = "py_traceability_rdf"
version = "0.0.0"
description = "A Python library providing RDF ontology definitions for requirement traceability across heterogeneous MBSE artifacts."
authors = ["Dirk Friedenberger <projekte@frittenburger.de>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/TheOpenMMTLab/traceability-rdf-model"

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
style = "semver"

[tool.poetry.dependencies]
python = "^3.9"
rdflib = ">=7.6.0"

[tool.poetry.group.dev.dependencies]
pytest = ">=7.0"

[build-system]
requires = ["poetry-core", "poetry-dynamic-versioning"]
build-backend = "poetry_dynamic_versioning.backend"
